services:
  app:
    build:
      dockerfile: Dockerfile
    volumes:
      - ".:/app"
    ports:
      - "8080:8080"
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
    env_file: ./.env