name: FastApi Docker build and push
on:
  push:
    branches: [ main ]
env:
  IMAGE_NAME: microservice_one
  REGISTRY: ghcr.io
  USERNAME: ${{ secrets.S_USER }}
  PASSWORD: ${{ secrets.S_TOKEN }}
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Print and Echo
        run: |
          echo "Hello, world!"
          echo ${{ env.USERNAME }} ${{ env.PASSWORD }} ${{ env.CGR_EJEMPLO }} ${{ secrets.CGR_EJEMPLO_USER }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Build and Push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry for pulling
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.USERNAME }}
          password: ${{ env.PASSWORD }}
      - name: Deploy Docker container
        run: |
          docker run -d -p 80:80 ${{ env.REGISTRY }}/${{ env.USERNAME }}/${{ env.IMAGE_NAME }}:${{github.sha}}
